# fly.toml app configuration file generated for index-weathered-shadow-2138 on 2025-07-27T17:27:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'index-weathered-shadow-2138'
primary_region = 'fra'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.tls_options]
alpn = ["h2", "http/1.1"]
versions = ["TLSv1.2", "TLSv1.3"]
default_self_signed = false

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
